### PR TITLE
some misc systemd-related improvements

### PR DESCRIPTION
**Pull request by danc86**
I can separate these commits into individual pull requests if you'd prefer.

The third patch in this series is not strictly systemd-related, it is about making the default secret generation step happen the first time the daemon starts, rather than at CMake installation time. I wrote these patches as part of creating an RPM package for Fedora.

### CODE REVIEW

**Comment by danc86** [comment]
Hmm Travis failed like this:

```
-- Detected init flavor: upstart
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBSYSTEMD
```

I guess I need to make the find_library() for systemd conditional on the init flavour.

**Comment by danc86** [comment]
Also I should probably tweak the socket activation patch to have four sockets instead of two: IPv4 and IPv6 for each of forward and reverse. I forgot that right now it is just listening on `[::1]` which IPv6 localhost, so connections to `127.0.0.1` won't get through.

**Comment by danc86** [comment]
I am also having second thoughts about whether the socket activation gains anything at all...

Originally I had in mind that it would make it possible to run postsrsd totally unprivileged, with all permission dropping done in systemd (and maybe some seccomp filters applied and everything). But I forgot that it needs to read the secrets file. That alone means it will have to keep running as root and dropping privs, even if the sockets are passed in by systemd.

The only advantage I can think of to socket activation is that it means postsrsd can now exit when it's idle and systemd will take care of starting it up whenever postfix wants to make a lookup. That might save a small amount of memory on very low traffic sites like mine. But the exit-on-idle behaviour would still need to be implemented.

**Comment by roehling** [comment]
I cherry-picked 1840c5f, because that fixes my biggest beef with the systemd config, the broken default domain.

Regarding the socket activation, I don't think it's worth the hassle. It adds special-case code for systemd which makes it behave differently than on all other systems, and the exit-on-idle behavior will save only a miniscule amount of memory on systems which most likely are idle with copious amounts of free RAM anyway.

**Comment by Natolumin** [comment]
What about generating the secret at rpm installation time in the specfile %pre ? It avoids the secret-inside-the-rpm problem without adding a 3-line shellscript in /usr/sbin for only this purpose.

**Comment by danc86** [comment]
Yes doing it in RPM %post would be the other option, the advantage to this approach here is that it keeps the logic of how to generate a good default secret in one place, in the source tree (as opposed to the RPM .spec) and consistently across all the packaging methods.

I was thinking of sshd, which follows a similar approach where sshd-keygen is run automatically at startup if host keys are missing.

**Comment by danc86** [comment]
@roehling thanks for applying the first commit. If you are interested in the third one (generate default secret at startup) I can file a new PR with just that one. Or if you'd prefer to keep it the way it is, you can just close this now.

**Comment by roehling** [comment]
I'll close this for now. The Debian/Ubuntu packages generate the secret at install time. For RPM, I think it should be done in the %post section as proposed.

**Pull request closed without merging**
